pull_request_rules:
  - name: squash dependency updates
    conditions:
      - author=dependabot[bot]
      - status-success=windows-latest - stable
    actions:
      merge:
        method: squash
  - name: squash reviewed prs
    conditions:
      - approved-reviews-by=jsim2010
      - status-success=windows-latest - stable
    actions:
      merge:
        method: squash
  - name: squash authored prs
    conditions:
      - author=jsim2010
      - label=automerge
      - status-success=windows-latest - stable
    actions:
      merge:
        method: squash
  - name: delete merged branches
    conditions: []
    actions:
      delete_head_branch: {}
