language: rust
cache: cargo
before_install:
  - rustup component add clippy
  - cargo install --force cargo-readme
script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose
