name: Check

on: pull_request

jobs:
  check:
    name: windows-latest - stable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
        if: contains(['opened', 'synchronize'], github.event_name)
      - uses: hecrj/setup-rust-action@v1.0.2
        with:
          rust-version: stable
        if: contains(['opened', 'synchronize'], github.event_name)
      - name: Build
        run: cargo build --verbose
        if: contains(['opened', 'synchronize'], github.event_name)
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
        if: contains(['opened', 'synchronize'], github.event_name)
      - name: Test
        run: cargo test --verbose
        if: contains(['opened', 'synchronize'], github.event_name)
