name: Merge

on: [check_suite, pull_request_review]
  standardize:
    name: Standardize
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install cargo-readme
        run: cargo install cargo-readme
      - name: Format
        run: cargo fmt
      - name: Update README
        run: cargo readme > README.md
      - uses: stefanzweifel/git-auto-commit-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: 'Standardize changes'
          COMMIT_AUTHOR_EMAIL: 'justinsimerly1992@gmail.com'
          COMMIT_AUTHOR_NAME: 'Justin Simerly'
        if: contains(github.event.pull_request.labels.*.name, 'ready')
