name: PR

on: pull_request

jobs:
  check:
    name: windows-latest - stable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
      - uses: hecrj/setup-rust-action@v1.0.2
        with:
          rust-version: stable
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
      - name: Build
        run: cargo build --verbose
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
      - name: Test
        run: cargo test --verbose
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
  merge:
    name: Merge
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1
      - name: Install cargo-readme
        run: cargo install cargo-readme
      - name: Format
        run: cargo fmt
      - name: Update README
        run: cargo readme > README.md
      - uses: stefanzweifel/git-auto-commit-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: 'Standardize changes'
          COMMIT_AUTHOR_EMAIL: 'justinsimerly1992@gmail.com'
          COMMIT_AUTHOR_NAME: 'Justin Simerly'
      - uses: pascalgn/automerge-action@v0.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
