name: Check

on: pull_request

jobs:
  lint:
    name: check lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: check lints
        run: cargo clippy --all-targets --all-features -- -D warnings
  format:
    name: check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: check format
        run: cargo fmt -- --check
  test:
    name: run tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Update rust to latest
        run: rustup update
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
